version: "2.2"
services:
  frontend:
    # uncomment for local dev
#    build: ./frontend
    restart: always
    image: gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/frontend:${VERSION}
    environment:
      - API_PASS=http://backend:5000
    ports:
      - ${PORT}:80
    links:
      - "backend:backend"
    depends_on:
      - backend

  backend:
    # uncomment for local dev
#    build: ./backend
    restart: always
    image: gitlab.zbmed.de:5050/km/nfdi4health/annotation-workbench/backend:${VERSION}
    expose:
      - "5000"
    environment:
      - PYTHONPATH=/workspace
      - API_SEMLOOKP=https://semanticlookup.zbmed.de/ols/api/
      - API_OLS=https://www.ebi.ac.uk/ols/api/
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - INSTRUMENTS=instruments
      - API_PREDICT=http://prediction:5000
    depends_on:
      - db
      - prediction
    volumes:
      - instruments:/var/lib/mda/instruments
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    ports:
      - ${PORT_DB}:${PORT_DB}
    volumes:
      - db:/var/lib/postgresql/data

  prediction:
    # uncomment for local dev
#    build: ./prediction
    restart: always
    image: gitlab.zbmed.de:5050/km/thesis/pierre-ba/backend:a7d3254ee488a236dade40ecedc646861aff9dbe
    expose:
      - "5000"

volumes:
  db:
  instruments: