name: Deployment to production
concurrency: production
on:
   workflow_dispatch:
    inputs:
      tags:
        description: 'Do you really want to update the production instance'
        required: false
        type: boolean
      image_sha:
        description: 'Image SHA ID, Optional '
        type: string
        required: false
env:
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_PROD }}
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p .kube
        echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG
    - uses: stefanprodan/kube-tools@v1
      with:
        helmv3: 3.12.0
        command: |
          helmv3 repo add mda-deployment https://nfdi4health.github.io/mda-deployment/
          helmv3 repo update
          helmv3 upgrade mda-prod  \
          --install \
          --set-json='images.backend="ghcr.io/${{ github.repository }}/backend:${{ github.event.pull_request.head.sha || github.sha }}"' \
          --set-json='images.frontend="ghcr.io/${{ github.repository }}/frontend:${{ github.event.pull_request.head.sha || github.sha }}"'  \
          --set-json='images.prediction="ghcr.io/nfdi4health/maelstrom-classification/backend:44a712a68697ce7d8dc544b7fd15cf0dd99e1d22"'  \
          --set-json='ingress.dns="mda.nfdi4health.de"'  \
          --set-json='ingress.enableSSL="true"'  \
          --set-json='ingress.certIssuer="letsencrypt-prod"'  \
          mda-deployment/metadata-annotation
